[package]
name = "savings-account"
version = "0.0.0"
authors = [ "Dorin Iancu <dorin.iancu@elrond.com>",]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[features]
wasm-output-mode = ["elrond-wasm-node"]

[dependencies.elrond-wasm]
version = "0.18.2"
features = ["derive"]

[dependencies.elrond-wasm-node]
version = "0.18.2"
optional = true

[dev-dependencies.elrond-wasm-debug]
version = "0.18.2"

[dependencies.price-aggregator-proxy]
git = "https://github.com/ElrondNetwork/sc-chainlink-rs"
rev = "15dac38"
