[package]
name = "savings-account-abi"
version = "0.0.0"
authors = [ "Dorin Iancu <dorin.iancu@elrond.com>",]
edition = "2018"
publish = false

[dependencies.savings-account]
path = ".."

[dependencies.elrond-wasm]
version = "0.18.2"

[dependencies.elrond-wasm-debug]
version = "0.18.2"
