name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  contracts:
    name: Contracts
    uses: ElrondNetwork/elrond-actions/.github/workflows/contracts.yml@v1
    with:
      rust-toolchain: nightly-2022-03-01
      vmtools-version: v1.4.43
      extra-build-args: --ignore-eei-checks
      pip-erdpy-args: https://github.com/ElrondNetwork/elrond-sdk-erdpy/archive/refs/heads/pin-cryptography-add-ledgercomm-hid.zip
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
